DROP DATABASE IF EXISTS EMAILDB;
CREATE DATABASE EMAILDB;

USE EMAILDB;


DROP TABLE IF EXISTS FOLDER;
CREATE TABLE FOLDER(
ID int(10) NOT NULL auto_increment,
name varchar(50) NOT NULL,
PRIMARY KEY (ID),
UNIQUE(name)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS MAIL;
CREATE TABLE MAIL(
ID int(10) NOT NULL auto_increment,
fromField varchar(100) NOT NULL,
subject varchar(100) NOT NULL,
textMessage varchar(1250) NOT NULL,
htmlMessage varchar(1250) NOT NULL,
mailStatus int(1) NOT NULL,
dateSent timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
dateReceived timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
folderID int(10) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (folderID) REFERENCES FOLDER(ID)
ON DELETE CASCADE
)ENGINE=InnoDB;

DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS(
ID int(10) NOT NULL auto_increment,
emailID int(10) NOT NULL,
email varchar(100) NOT NULL,
typeField char(3) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY(emailID) REFERENCES MAIL(ID)
ON DELETE CASCADE
)ENGINE=InnoDB;

DROP TABLE IF EXISTS ATTACHMENT;
CREATE TABLE ATTACHMENT(
ID int(10) NOT NULL auto_increment,
emailID int(10) NOT NULL,
contentID varchar(60) NOT NULL,
name varchar(250) NOT NULL,
size int(100) NOT NULL,
content MEDIUMBLOB NOT NULL,
typeField char(3) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (emailID) REFERENCES MAIL(ID)
ON DELETE CASCADE
)ENGINE=InnoDB;


